# Generated by Django 6.0 on 2026-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='application',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
