# Generated by Django 6.0 on 2026-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='delivery_type',
            field=models.CharField(choices=[('panchayat', 'Pickup from Panchayat'), ('taluka', 'Pickup from Taluka'), ('courier', 'Courier Delivery')], default='panchayat', max_length=20),
        ),
    ]
